//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSConversorUnidadesClienteESC.LoginServicioReferencia {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoginServicioReferencia.ILoginServicio")]
    public interface ILoginServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginServicio/Login", ReplyAction="http://tempuri.org/ILoginServicio/LoginResponse")]
        bool Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginServicio/Login", ReplyAction="http://tempuri.org/ILoginServicio/LoginResponse")]
        System.Threading.Tasks.Task<bool> LoginAsync(string username, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoginServicioChannel : WSConversorUnidadesClienteESC.LoginServicioReferencia.ILoginServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginServicioClient : System.ServiceModel.ClientBase<WSConversorUnidadesClienteESC.LoginServicioReferencia.ILoginServicio>, WSConversorUnidadesClienteESC.LoginServicioReferencia.ILoginServicio {
        
        public LoginServicioClient() {
        }
        
        public LoginServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Login(string username, string password) {
            return base.Channel.Login(username, password);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(string username, string password) {
            return base.Channel.LoginAsync(username, password);
        }
    }
}
