//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSConversorUnidadesClienteWEB.ConversorLongitudServicioReferencia {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConversorLongitudServicioReferencia.IConversorLongitudServicio")]
    public interface IConversorLongitudServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversorLongitudServicio/ConvertirLongitud", ReplyAction="http://tempuri.org/IConversorLongitudServicio/ConvertirLongitudResponse")]
        double ConvertirLongitud(double valor, string unidadOrigen, string unidadDestino);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversorLongitudServicio/ConvertirLongitud", ReplyAction="http://tempuri.org/IConversorLongitudServicio/ConvertirLongitudResponse")]
        System.Threading.Tasks.Task<double> ConvertirLongitudAsync(double valor, string unidadOrigen, string unidadDestino);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConversorLongitudServicioChannel : WSConversorUnidadesClienteWEB.ConversorLongitudServicioReferencia.IConversorLongitudServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConversorLongitudServicioClient : System.ServiceModel.ClientBase<WSConversorUnidadesClienteWEB.ConversorLongitudServicioReferencia.IConversorLongitudServicio>, WSConversorUnidadesClienteWEB.ConversorLongitudServicioReferencia.IConversorLongitudServicio {
        
        public ConversorLongitudServicioClient() {
        }
        
        public ConversorLongitudServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConversorLongitudServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConversorLongitudServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConversorLongitudServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double ConvertirLongitud(double valor, string unidadOrigen, string unidadDestino) {
            return base.Channel.ConvertirLongitud(valor, unidadOrigen, unidadDestino);
        }
        
        public System.Threading.Tasks.Task<double> ConvertirLongitudAsync(double valor, string unidadOrigen, string unidadDestino) {
            return base.Channel.ConvertirLongitudAsync(valor, unidadOrigen, unidadDestino);
        }
    }
}
